language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev

script: vendor/bin/phpunit tests/CI_Base_Model_test.php